/* AGENTIC-ARBITER -- charts/primitives.mjs
   ============================================================================================
   GENERATED by tools/mkcore.py, lifted byte for byte out of demo/index.html's inline script
   by the same brace-matching extractor the node verifiers use. Do not hand-edit until the page has
   been switched over to import it; until then demo/index.html holds the live copy and
   verify_core_equivalence.mjs asserts the two agree on every case in all four corpora.

   THE ONLY DELIBERATE CHANGE from the inline original is that the three artefact globals the page
   kept in scope are now ARGUMENTS. That is what makes these functions importable at all, and it is
   why the verifiers no longer need to stub the DOM to test the agent.
   ============================================================================================ */

/* THE LAYER UNDER EVERY PANEL, and the only part of the 3,621 lines of drawing code that is worth
   lifting verbatim. The 31 draw* functions are panel renderers: each one writes innerHTML as well as
   painting canvas, so each has to be REBUILT as a component rather than moved. These seven do not:
   they are primitives, they are shared, and a React chart component needs all of them on day one. */

/* fitCanvas caps the device-pixel-ratio here */
export const DPR_CAP = 2;

/* casePath reads this to case a mark in its colourblind-safe edge tone */
export const EDGE = {'--series-1':'--series-1-edge', '--series-2':'--series-2-edge'};

export function motionOK(){
  try{ return !window.matchMedia('(prefers-reduced-motion: reduce)').matches; }
  catch(e){ return true; }
}

export function getCssVar(name){
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim() || '#888';
}

export function fitCanvas(c, cssW, cssH){
  if(!c.dataset.logh) c.dataset.logh = String(c.height);
  if(!c.dataset.logw) c.dataset.logw = String(c.width);
  if(cssH == null) cssH = +c.dataset.logh;
  if(cssW == null) cssW = +c.dataset.logw;
  cssW = Math.max(1, Math.round(cssW));
  cssH = Math.max(1, Math.round(cssH));
  const dpr = Math.min(DPR_CAP, Math.max(1, window.devicePixelRatio || 1));
  const bw = Math.round(cssW * dpr), bh = Math.round(cssH * dpr);
  /* Assigning width/height CLEARS the canvas, so only touch them when they actually change --
     otherwise the crosshair repaint in drawBound would wipe the chart it is drawing over. */
  if(c.width !== bw || c.height !== bh){ c.width = bw; c.height = bh; }
  c.style.width = cssW + 'px';
  c.style.height = cssH + 'px';
  const g = c.getContext('2d');
  g.setTransform(dpr, 0, 0, dpr, 0, 0);
  return {W: cssW, H: cssH, g: g, dpr: dpr};
}

export function casePath(g, tok, w, path){
  g.lineJoin = 'round'; g.lineCap = 'round';
  g.strokeStyle = cssv(EDGE[tok] || tok); g.lineWidth = w + 1.6;
  g.beginPath(); path(); g.stroke();
  g.strokeStyle = cssv(tok); g.lineWidth = w;
  g.beginPath(); path(); g.stroke();
}

export function chipText(g, txt, x, y, align){
  g.textAlign = align || 'left';
  const w = g.measureText(txt).width, padX = 4, padY = 2.5;
  const h = 11;                                      /* the cap height these labels are drawn at */
  const left = align === 'right' ? x - w : align === 'center' ? x - w / 2 : x;
  const prev = g.fillStyle;
  g.fillStyle = cssv('--surface-1');
  g.fillRect(left - padX, y - h - padY, w + 2 * padX, h + 2 * padY + 2);
  g.fillStyle = prev;
  g.fillText(txt, x, y);
}

export function sparkSVG(vals, cap){
  const v = (vals || []).filter(x => typeof x === 'number' && isFinite(x));
  if(v.length < 2) return '';
  const lo = Math.min(...v), hi = Math.max(...v), span = (hi - lo) || 1;
  const W = 100, H = 28, pad = 2.5;
  const X = i => (i / (v.length - 1)) * W;
  const Y = x => H - pad - ((x - lo) / span) * (H - 2 * pad);
  const pts = v.map((x, i) => X(i).toFixed(2) + ',' + Y(x).toFixed(2));
  const line = 'M' + pts.join('L');
  const area = line + 'L' + W + ',' + H + 'L0,' + H + 'Z';
  const lx = X(v.length - 1).toFixed(2), ly = Y(v[v.length - 1]).toFixed(2);
  return '<svg class="spark" viewBox="0 0 ' + W + ' ' + H + '" preserveAspectRatio="none" '
       + 'aria-hidden="true" focusable="false">'
       + '<path class="sp-area" d="' + area + '"/>'
       + '<path class="sp-line" d="' + line + '"/>'
       + '<circle class="sp-dot" cx="' + lx + '" cy="' + ly + '" r="2.2"/>'
       + '</svg>'
       + (cap ? '<div class="spark-cap">' + cap + '</div>' : '');
}

export function countUpText(el){
  const target = el.textContent;
  if(!target || target.indexOf('<') >= 0 || !motionOK()){ return; }
  const parts = target.match(/(\d[\d,]*(?:\.\d+)?)|([^\d]+)/g);
  if(!parts) return;
  const spec = parts.map(p => {
    const m = /^\d[\d,]*(?:\.\d+)?$/.test(p);
    if(!m) return {lit: p};
    const grouped = p.indexOf(',') >= 0;
    const dot = p.indexOf('.');
    return {num: parseFloat(p.replace(/,/g, '')),
            dp: dot < 0 ? 0 : p.length - dot - 1,
            grouped: grouped};
  });
  if(!spec.some(s => s.num !== undefined)) return;
  const t0 = performance.now();
  const render = (k) => el.textContent = spec.map(s => {
    if(s.lit !== undefined) return s.lit;
    let v = (s.num * k).toFixed(s.dp);
    if(s.grouped){
      const bits = v.split('.');
      bits[0] = bits[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',');
      v = bits.join('.');
    }
    return v;
  }).join('');
  const step = (now) => {
    const p = Math.min(1, (now - t0) / COUNT_MS);
    /* The same easing the CSS uses, so a card whose figure counts while its own edge settles reads
       as one motion rather than two. Cubic ease-out, and it ENDS exactly on 1 -- a spring that
       overshoots would show 10.9 % before settling on 10.7 %, i.e. print a number that is not true
       for a few frames, which on this page is not an acceptable flourish. */
    render(1 - Math.pow(1 - p, 3));
    if(p < 1) requestAnimationFrame(step); else el.textContent = target;
  };
  requestAnimationFrame(step);
}

/* ---- THE CANVAS FONT TABLE ------------------------------------------------------------------
   🔴 RESOLVED FROM THE CSS TOKENS, NOT DUPLICATED FROM THEM. index.html declares CFACE/CMONO/CBODY
   as string literals repeating the font stacks in --font-display/--font-mono/--font-body, and its own
   comment concedes the problem: "Keep the two in step by hand; there is no mechanical guard available
   and pretending otherwise is the drift this codebase keeps documenting."
   A guard does exist; it just was not reachable there. `getCssVar` sits 3,700 lines below CF in the
   page, so CF could not call it at declaration time. In a module the order is ours, and making CF an
   object of GETTERS defers the lookup to first use -- after the stylesheet is parsed, and with no
   change at any of the 40 fillText call sites, which still write `g.font = CF.label`.
   Cached because getComputedStyle is not free and a chart sets its font per label. Fonts do not
   change with the theme, so the cache never needs invalidating. */
let _F = null;
const faces = () => (_F || (_F = {
  face: getCssVar('--font-display'),
  mono: getCssVar('--font-mono'),
  body: getCssVar('--font-body')
}));

export const CF = {
  get tick()       { return '9px '      + faces().mono; },  /* densest axis figures */
  get axis()       { return '10px '     + faces().mono; },  /* tick and gridline figures */
  get axisStrong() { return '600 10px ' + faces().face; },  /* the one emphasised axis LABEL */
  get label()      { return '11px '     + faces().face; },  /* series names, compass letters */
  get message()    { return '13px '     + faces().body; }   /* empty and loading states */
};
