/* AGENTIC-ARBITER -- core/agent.mjs
   ============================================================================================
   GENERATED by tools/mkcore.py, lifted byte for byte out of demo/index.html's inline script
   by the same brace-matching extractor the node verifiers use. Do not hand-edit until the page has
   been switched over to import it; until then demo/index.html holds the live copy and
   verify_core_equivalence.mjs asserts the two agree on every case in all four corpora.

   THE ONLY DELIBERATE CHANGE from the inline original is that the three artefact globals the page
   kept in scope are now ARGUMENTS. That is what makes these functions importable at all, and it is
   why the verifiers no longer need to stub the DOM to test the agent.
   ============================================================================================ */

/* Imports DERIVED by mkcore.py from the names this file actually uses. See the note in
   the generator: a hand-written list here already cost the explanation corpus once. */
import { fmt } from "./format.mjs";

export function H0(ds){ return ds.hours.length; }

export function plan(safe,budget,dwell){
  const D=Math.max(1,dwell);
  let cur=new Map([[`0|0|0`,{f:0,s:0,p:[]}]]);
  for(let h=0;h<safe.length;h++){
    const nx=new Map();
    for(const [key,st] of cur){
      const [m,u,dl]=key.split('|').map(Number);
      for(const nm of [m,1-m]){
        let nu,ndl;
        if(nm===m){ nu=u; ndl=Math.max(0,dl-1); }
        else { if(dl>0||u>=budget) continue; nu=u+1; ndl=Math.max(0,D-1); }
        if(nm===1 && !safe[h]) continue;
        const kk=`${nm}|${nu}|${ndl}`, f=st.f+(nm===1?1:0);
        const old=nx.get(kk);
        if(!old || f>old.f || (f===old.f && nu<old.s))
          nx.set(kk,{f,s:nu,p:st.p.concat(nm)});
      }
    }
    if(!nx.size) return {modes:new Array(safe.length).fill(0),sw:0};
    cur=nx;
  }
  let best=null; for(const st of cur.values())
    if(!best||st.f>best.f||(st.f===best.f&&st.s<best.s)) best=st;
  return {modes:best.p, sw:best.s};
}

export function reactive(safe,budget,dwell){
  const D=Math.max(1,dwell); let m=0,u=0,dl=0,over=0; const modes=[];
  for(let h=0;h<safe.length;h++){
    const want=safe[h]?1:0;
    if(want!==m){
      if(dl===0&&u<budget){ m=want;u++;dl=Math.max(0,D-1); }
      else if(want===0){ m=0;u++;dl=0;over++; }
      else dl=Math.max(0,dl-1);
    } else dl=Math.max(0,dl-1);
    modes.push(m);
  }
  return {modes,sw:u,over};
}

/* 🔴 `decide` GAINED ONE PARAMETER, `trace`, and lost its reach into the module-scope
   global `T`. That global is the per-site artefact the page happens to have loaded, which
   meant the agent's behaviour depended on page state rather than on its arguments -- the
   reason verify_browser_decision.js has to stub the browser before it can test anything. */
export function decide(k, trace){
  const ds=trace.cases.day_series[k.case];
  if(!ds) return null;
  const N=k.notice, H=ds.hours.length;
  const rise=ds['rise_c_'+k.bank], refused=ds['refused_'+k.bank];
  // The agent sees the rise at the FORECAST bearing and carries a per-hour plume margin; the
  // truth uses the bearing that actually occurred. Keeping these separate is what makes the
  // browser's decision identical to the Python agent's rather than merely similar.
  const riseTrue=ds['rise_true_c_'+k.bank]||rise;
  const plumeM=ds['plume_margin_c_'+k.bank]||new Array(H0(ds)).fill(0);
  const rp=ds['r_prime|'+N]||new Array(H).fill(0);
  const rwp=ds['rw_prime|'+N]||new Array(H).fill(0);
  const md=ds['margin_dry|'+N]||new Array(H).fill(0);
  const mw=ds['margin_wet|'+N]||new Array(H).fill(0);
  const rdp=ds['rdp_prime|'+N]||new Array(H).fill(0);
  const mdp=ds['margin_dp|'+N]||new Array(H).fill(0);
  const idp=ds['incumbent_dp_src|'+N]||ds.dewpoint_c;
  const isrc=ds['incumbent_src|'+N], iwsrc=ds['incumbent_wet_src|'+N];
  /* THE FORTYGUARD LEVEL TERM. Two separate quantities, and conflating them was a real bug:
       `off` is the day's MEASURED offset -- an input error the unanchored agent inherits, so it is
             SUBTRACTED from the forecast;
       `lvl` is the leave-one-out conformal margin bounding how wrong that level can be, so it is
             ADDED to the bound.
     Both are read from `trace.cases.fg_offsets`, the table agent.py computes once and ships.

     WHAT THIS REPLACED. This block used to reduce trace.cycle.pairs to the single worst-MAGNITUDE
     offset and add no margin at all. That disagreed with the Python agent on 2,588 of 8,064
     unanchored configurations -- 32.1 % -- and verify_browser_decision.js could not see it because
     it filtered to anchor === 'sensor'. It also reproduced the oracle gotcha #48 records: ONE
     constant offset across 1,826 days gave +450.9 h/yr where the four measured offsets rotated
     gave -156.0. The filter is gone and all four offsets are selectable. */
  const offs=(trace.cases.fg_offsets||[]);
  let off=0, lvl=0, offLabel='anchored: one local reading removes the day level';
  if(k.anchor==='none'){
    const o=offs.find(x=>x.date===k.offday)||offs[0];
    if(!o) return null;
    off=o.mean_d; lvl=o.level_margin_c;
    offLabel='unanchored: <strong>FortyGuard</strong>\'s measured offset for '+o.date+' ('+fmt(off,4)+' °C), '
      +'bounded by a leave-one-out conformal margin of '+fmt(lvl,4)+' °C fitted on the other '
      +o.level_n+' measured days'+(o.level_clamped?' (CLAMPED: guarantee degraded)':'');
  }
  const s=1-k.skill;
  const ubD=[], ubW=[], ubP=[], safeA=[], safeI=[], truth=[], truthW=[];
  for(let h=0;h<H;h++){
    const fc = ds.temp_c[h] - off - s*rp[h];
    const bd = fc + lvl + s*md[h] + rise[h] + plumeM[h];
    /* `off` IS A TEMPERATURE OFFSET AND IT APPLIES ONLY TO THE TEMPERATURE CHANNEL.
       mean_d is measured as (outcome - forecast) on <strong>FortyGuard</strong>'s HEATMAP, which is dry-bulb. There
       is no measured FortyGuard dew-point offset -- we hold no dew-point forecast/outcome pair --
       so applying this one to humidity would be an invented assumption, and agent.py does not.
       These two lines used to subtract it anyway, which flipped the dew-point gate on unanchored
       days: at the -3.7127 C offset the browser's dew-point bound ran 3.7 C high and closed a gate
       the agent had left open. 1,541 of 20,160 configurations, all of them unanchored.
       The level MARGIN is still added, because that is what the agent does: a temperature-derived
       margin on a humidity bound is conservative, and it is the audited behaviour. */
    const fw = ds.twb_c[h] - s*rwp[h];
    const bw = fw + lvl + s*mw[h];
    const bp = ds.dewpoint_c[h] - s*rdp[h] + lvl + s*mdp[h];
    ubD.push(bd); ubW.push(bw); ubP.push(bp);
    truth.push(ds.temp_c[h]+riseTrue[h]); truthW.push(ds.twb_c[h]);
    const gd = bd<=k.limit;
    const gw = k.dp===null ? true : bp<=k.dp;
    const ga = (k.aq===null||!ds.aq_idx) ? true : ds.aq_idx[h]<=k.aq;
    safeA.push(gd && gw && ga && !refused[h]);
    const gwi = k.dp===null ? true : (idp[h]+mdp[h])<=k.dp;
    const gai = ga;
    safeI.push((isrc[h]+md[h])<=k.limit && gwi && gai);
  }
  const A=plan(safeA,k.budget,k.dwell), I=reactive(safeI,k.budget,k.dwell);
  const trulySafe = truth.map((v,h)=> v<=k.limit && (k.dp===null || ds.dewpoint_c[h]<=k.dp));
  const cnt=(m,f)=>m.reduce((a,x,h)=>a+((x===1&&f(h))?1:0),0);
  const mShape = md.map(v=>s*v);   // the ACTUAL shape margin, not a back-subtraction
  return {k,ds,H,rise,riseTrue,plumeM,mShape,rp,rdp,md,mdp,refused,ubD,ubW,ubP,truth,trulySafe,
    safeA,safeI,off,lvl,offLabel,
    A,I, aFree:A.modes.filter(x=>x===1).length, iFree:I.modes.filter(x=>x===1).length,
    aBreach:cnt(A.modes,h=>!trulySafe[h]), iBreach:cnt(I.modes,h=>!trulySafe[h]),
    aRef:refused.filter(Boolean).length};
}
