/* AGENTIC-ARBITER -- core/conformal.mjs
   ============================================================================================
   GENERATED by scratchpad/mkcore.py, lifted byte for byte out of demo/index.html's inline script
   by the same brace-matching extractor the node verifiers use. Do not hand-edit until the page has
   been switched over to import it; until then demo/index.html holds the live copy and
   verify_core_equivalence.mjs asserts the two agree on every case in all four corpora.

   THE ONLY DELIBERATE CHANGE from the inline original is that the three artefact globals the page
   kept in scope are now ARGUMENTS. That is what makes these functions importable at all, and it is
   why the verifiers no longer need to stub the DOM to test the agent.
   ============================================================================================ */

/* ALL FOUR WERE ALREADY PURE. Not one substitution was needed in this file, which is the strongest
   thing that can be said about the conformal implementation: the split, the quantile index, the
   attainable-coverage ceiling and the minimum-n floor never touched a global or the document. */

export function cfMinN(alpha){ return Math.ceil(1 / alpha) - 1; }

export function cfAttainable(n){ return n > 0 ? n / (n + 1) : 0; }

export function cfQuantileIndex(n, alpha){
  const k = Math.ceil((n + 1) * (1 - alpha));
  return {k: Math.min(k, n), clamped: k > n};
}

export function cfSplit(res, alpha){
  const r = res.filter(x => x !== null && x !== undefined && !Number.isNaN(+x))
               .map(Number).sort((a, b) => a - b);
  const n = r.length;
  if(!n) return {q: NaN, n: 0, k: 0, clamped: true, ceiling: 0, nominal: 1 - alpha, sorted: []};
  const ki = cfQuantileIndex(n, alpha);
  return {q: r[ki.k - 1], n, k: ki.k, clamped: ki.clamped,
          ceiling: cfAttainable(n), nominal: 1 - alpha, sorted: r};
}

