/* AGENTIC-ARBITER -- core/config.mjs
   ============================================================================================
   GENERATED by tools/mkcore.py, lifted byte for byte out of demo/index.html's inline script
   by the same brace-matching extractor the node verifiers use. Do not hand-edit until the page has
   been switched over to import it; until then demo/index.html holds the live copy and
   verify_core_equivalence.mjs asserts the two agree on every case in all four corpora.

   THE ONLY DELIBERATE CHANGE from the inline original is that the three artefact globals the page
   kept in scope are now ARGUMENTS. That is what makes these functions importable at all, and it is
   why the verifiers no longer need to stub the DOM to test the agent.
   ============================================================================================ */

/* 🔴 THE CONTRACT, NOT THE CONTROL. `get` is a callback that returns the STRING for a control id, so
   the page passes `id => $(id).value` and a test passes `id => String(row[...])`. Both then run the
   identical eleven coercions below.
   That matters more than it looks. A <select> always yields a string, so `offday` is "0" and not 0,
   and `dp`/`aq` are null exactly when the control reads "off". A test that assembled this object from
   scenarios.json's raw JSON types would hand the agent a number where the page hands it a string, and
   nothing would report the difference. */

export function cfgFromStrings(get){
  const v=id=>get(id);
  return { case:v('#c_case'), limit:+v('#c_limit'), notice:+v('#c_notice'),
    anchor:v('#c_anchor'), skill:+v('#c_skill'), bank:v('#c_bank'),
    budget:+v('#c_budget'), dwell:+v('#c_dwell'), offday:v('#c_offday'),
    dp: v('#c_wb')==='off'?null:+v('#c_wb'),
    aq: v('#c_aq')==='off'?null:+v('#c_aq') };
}
