/* AGENTIC-ARBITER -- core/explain.mjs
   ============================================================================================
   GENERATED by scratchpad/mkcore.py, lifted byte for byte out of demo/index.html's inline script
   by the same brace-matching extractor the node verifiers use. Do not hand-edit until the page has
   been switched over to import it; until then demo/index.html holds the live copy and
   verify_core_equivalence.mjs asserts the two agree on every case in all four corpora.

   THE ONLY DELIBERATE CHANGE from the inline original is that the three artefact globals the page
   kept in scope are now ARGUMENTS. That is what makes these functions importable at all, and it is
   why the verifiers no longer need to stub the DOM to test the agent.
   ============================================================================================ */

/* Imports DERIVED by mkcore.py from the names this file actually uses. See the note in
   the generator: a hand-written list here already cost the explanation corpus once. */
import { plan } from "./agent.mjs";
import { fmt } from "./format.mjs";

export function explainHour(R, h) {
  const k = R.k, free = R.A.modes[h] === 1;
  const dryPass = R.ubD[h] <= k.limit;
  const dewPass = k.dp === null ? true : R.ubP[h] <= k.dp;
  const aqPass = (k.aq === null || !R.ds.aq_idx) ? true : R.ds.aq_idx[h] <= k.aq;
  const refused = R.refused[h];
  // Use the margin the agent actually applied. Deriving it by subtracting the other terms out of
  // the bound accumulates float error and printed "-0.000 C", which reads as a broken number in a
  // sentence whose whole point is that the margin is measured.
  const shape = R.mShape ? R.mShape[h] : 0;
  const e = { hour: R.ds.hours[h], mode: free ? 'FREE-COOLING' : 'MECHANICAL',
              safe: R.safeA[h], binding: null };

  if (free) {
    e.why = 'Free cooling. The upper bound on intake air is ' + fmt(R.ubD[h], 3) + ' °C, '
      + fmt(k.limit - R.ubD[h], 3) + ' °C under the ' + fmt(k.limit, 1) + ' °C limit. '
      + 'The margin is measured, not chosen: ' + fmt(shape, 3) + ' °C of group-conditional '
      + 'forecast error for this hour of day, plus ' + fmt(R.plumeM[h], 4) + ' °C for how far '
      + 'the plume could move given the wind-direction error <strong>FortyGuard</strong> actually has.';
    if (R.truth[h] > k.limit)
      e.why += ' ⚠ THIS WAS WRONG: the intake actually reached ' + fmt(R.truth[h], 3)
             + ' °C. Counted as a breach, not explained away.';
    return e;
  }
  if (refused) {
    e.binding = 'refusal';
    e.why = 'Mechanical, and the reason is a REFUSAL rather than a temperature. At this bearing a '
          + 'building sits between the condensers and the intake. The dispersion model has no '
          + 'representation of a building standing in the flow, so any number it produced would be '
          + 'meaningless — so the agent declines to certify the hour.';
    return e;
  }
  if (!dryPass || !dewPass || !aqPass) {
    const cands = [];
    if (!dryPass) cands.push(['dry-bulb', R.ubD[h] - k.limit]);
    if (!dewPass) cands.push(['dew point', R.ubP[h] - k.dp]);
    if (!aqPass) cands.push(['air quality', R.ds.aq_idx[h] - k.aq]);
    cands.sort((a, b) => b[1] - a[1]);
    e.binding = cands[0][0]; e.flip_needs = cands[0][1];
    if (e.binding === 'dry-bulb')
      e.why = 'Mechanical. The upper bound on intake is ' + fmt(R.ubD[h], 3) + ' °C against a '
            + fmt(k.limit, 1) + ' °C limit — it fails by ' + fmt(e.flip_needs, 3)
            + ' °C. A limit that much higher, or a bound that much tighter, would change it.';
    else if (e.binding === 'dew point')
      e.why = 'Mechanical, and TEMPERATURE IS NOT THE REASON — the dry-bulb bound of '
            + fmt(R.ubD[h], 3) + ' °C would have passed. The air is too HUMID: dew-point bound '
            + fmt(R.ubP[h], 2) + ' °C against a ' + fmt(k.dp, 1) + ' °C maximum, failing by '
            + fmt(e.flip_needs, 2) + ' °C. Cool but damp air condenses on cold surfaces inside '
            + 'the hall, which is why real economizers gate on humidity, not temperature alone.';
    else
      e.why = 'Mechanical, and neither temperature nor humidity is the reason. The air is too '
            + 'DIRTY: PM2.5 index ' + fmt(R.ds.aq_idx[h], 1) + ' against a ' + fmt(k.aq, 1)
            + ' limit. Opening a damper pulls that air into the hall — the documented reason '
            + 'operators avoid free cooling at all.';
    if (cands.length > 1) e.also = cands.slice(1).map(c => c[0]);
    return e;
  }
  // safe, yet mechanical: the planner declined. Which constraint? Re-plan to find out.
  const byBudget = plan(R.safeA, k.budget + 2, k.dwell).modes[h] === 1;
  const byDwell = plan(R.safeA, k.budget, 1).modes[h] === 1;
  e.binding = (byBudget && !byDwell) ? 'switch budget'
            : (byDwell && !byBudget) ? 'minimum dwell'
            : byBudget ? 'switch budget' : null;
  e.why = 'Mechanical EVEN THOUGH THIS HOUR IS SAFE — every gate passes, the bound is '
        + fmt(R.ubD[h], 3) + ' °C against ' + fmt(k.limit, 1) + ' °C. The SCHEDULE forbids '
        + 'it: ' + (byBudget ? 'the switch budget of ' + k.budget + ' changes per day is already '
        + 'committed to better hours' : byDwell ? 'the plant must hold its mode for ' + k.dwell
        + ' h before changing again' : 'relaxing neither the budget nor the dwell would free it, so '
        + 'the surrounding hours are worth more') + '. This is the one explanation a thermostat '
        + 'cannot give, because a thermostat has no plan to be constrained by.';
  return e;
}
