/* AGENTIC-ARBITER -- core/format.mjs
   ============================================================================================
   GENERATED by scratchpad/mkcore.py, lifted byte for byte out of demo/index.html's inline script
   by the same brace-matching extractor the node verifiers use. Do not hand-edit until the page has
   been switched over to import it; until then demo/index.html holds the live copy and
   verify_core_equivalence.mjs asserts the two agree on every case in all four corpora.

   THE ONLY DELIBERATE CHANGE from the inline original is that the three artefact globals the page
   kept in scope are now ARGUMENTS. That is what makes these functions importable at all, and it is
   why the verifiers no longer need to stub the DOM to test the agent.
   ============================================================================================ */

/* `fmt` is shared by decide() and explainHour(), and it is the reason a bound of 6.4 C reads the
   same way in the schedule and in the sentence that explains the schedule. One copy, imported. */
export const fmt = (v,d=2) => (v===null||v===undefined||Number.isNaN(v)) ? '–' : (+v).toFixed(d);
