/* AGENTIC-ARBITER -- core/ticker.mjs
   ============================================================================================
   GENERATED by tools/mkcore.py, lifted byte for byte out of demo/index.html's inline script
   by the same brace-matching extractor the node verifiers use. Do not hand-edit until the page has
   been switched over to import it; until then demo/index.html holds the live copy and
   verify_core_equivalence.mjs asserts the two agree on every case in all four corpora.

   THE ONLY DELIBERATE CHANGE from the inline original is that the three artefact globals the page
   kept in scope are now ARGUMENTS. That is what makes these functions importable at all, and it is
   why the verifiers no longer need to stub the DOM to test the agent.
   ============================================================================================ */

export function tkFixed(x, n){
  const s = x.toFixed(20), dot = s.indexOf('.');
  const digits = s.slice(0, dot) + s.slice(dot + 1);
  const cut = dot + n;                       /* keep this many digits from the left */
  let keep = digits.slice(0, cut);
  const rest = digits.slice(cut);
  let up = false;
  if(rest.length){
    const first = rest[0];
    if(first > '5') up = true;
    else if(first === '5'){
      /* strictly above half rounds up; an EXACT half rounds to even, as Python does */
      up = /[1-9]/.test(rest.slice(1)) ? true
         : ((keep.charCodeAt(keep.length - 1) - 48) % 2) === 1;
    }
  }
  if(up){
    const a = keep.split(''); let i = a.length - 1;
    for(; i >= 0; i--){ if(a[i] === '9') a[i] = '0'; else { a[i] = String(+a[i] + 1); break; } }
    keep = (i < 0 ? '1' : '') + a.join('');
  }
  let ip = n ? keep.slice(0, keep.length - n) : keep;
  const fp = n ? keep.slice(keep.length - n) : '';
  ip = ip.replace(/^0+(?=\d)/, '');
  if(ip === '') ip = '0';
  return n ? ip + '.' + fp : ip;
}

export function tkRender(tpl, vals){
  return tpl.replace(/\x7B([A-Za-z_][A-Za-z0-9_]*)(?::([^\x7D]*))?\x7D/g, (_m, k, spec)=>{
    if(!(k in vals)) throw new Error('ticker: template asks for '+k+' and the payload has not got it');
    return tkFormat(vals[k], spec === undefined ? '' : spec);
  });
}

/* PURE, and verified so: the only `US` in this function is the locale tag in
   toLocaleString('en-US'). It reads no global. */
export function tkFormat(v, spec){
  if(typeof v === 'boolean'){
    if(spec) throw new Error('ticker: a yes/no value takes no format spec, got '+spec);
    return v ? 'yes' : 'no';
  }
  if(spec === ''){
    if(typeof v === 'number') throw new Error('ticker: a number needs an explicit format spec');
    return String(v);
  }
  if(spec === ','){
    if(+v !== Math.trunc(+v)) throw new Error('ticker: the thousands spec is for whole numbers');
    return Math.trunc(+v).toLocaleString('en-US');
  }
  const m = /^(\+?)\.(\d+)f$/.exec(spec);
  if(m){
    let x = +v;
    if(!Number.isFinite(x)) throw new Error('ticker: refusing to render a non-finite number');
    if(x === 0) x = 0;              /* -0 renders "-0.0000" in Python and "0.0000" here */
    const s = tkFixed(Math.abs(x), +m[2]);
    return (x < 0 ? '-' : (m[1] === '+' ? '+' : '')) + s;
  }
  throw new Error('ticker: unsupported format spec '+spec);
}

export function tkEvent(code, vals, tk){
  const d = tk && tk.templates && tk.templates[code];
  if(!d) throw new Error('ticker: no template for '+code);
  return {code, stage:d.stage, stage_name:tk.stages[String(d.stage)],
          numbers:vals, text:tkRender(d.template, vals)};
}

export function tickerFor(R, h, tk){
  /* GENERATED: binds the ticker artefact for the twelve tkEvent calls below, so the
     substitution that carries it is an identifier rename rather than twelve bracket-matched
     argument insertions. */
  const _ev = (c, v) => tkEvent(c, v, tk);

  const k = R.k, ds = R.ds, s = 1 - k.skill, out = [];
  const drct = ds.wind_from_deg[h], kt = ds.wind_kt[h];
  const calm = (drct === null || kt === null || kt < tk.calm_kt);
  const bearing = drct === null ? 0 : ds['bearing_forecast_deg_'+k.bank][h];
  const bound = R.ubD[h], truth = R.truth[h];
  let used = 0; for(let i=1;i<=h;i++) if(R.A.modes[i] !== R.A.modes[i-1]) used++;

  out.push(_ev('hour.perceive', {hour_label: ds.hours[h]+':00',
    fc_c: ds.temp_c[h] - R.off - s*R.rp[h],
    fc_dp_c: ds.dewpoint_c[h] - s*R.rdp[h],
    notice_h: k.notice, skill: k.skill}));

  if(R.refused[h])      out.push(_ev('hour.solve_refused', {bearing_deg: bearing}));
  else if(calm)         out.push(_ev('hour.solve_calm', {rise_c: R.rise[h]}));
  else {
    const head = k.limit - ds.temp_c[h];
    if(head > 0) out.push(_ev('hour.solve', {bearing_deg: bearing, wind_kt: kt,
      rise_c: R.rise[h], rise_pct: 100*R.rise[h]/head}));
    else out.push(_ev('hour.solve_no_headroom', {bearing_deg: bearing, wind_kt: kt,
      rise_c: R.rise[h], over_c: -head}));
  }

  out.push(_ev('hour.bound', {margin_c: R.lvl + R.mShape[h] + R.plumeM[h],
    shape_c: R.mShape[h], plume_c: R.plumeM[h], level_c: R.lvl, bound_c: bound}));

  if(R.safeA[h]) out.push(_ev('hour.decide_free',
                    {bound_c: bound, limit_c: k.limit, slack_c: k.limit - bound}));
  else {
    /* the binding constraint, in the same precedence order explain.py uses */
    const binding = R.refused[h] ? 'refusal'
      : bound > k.limit ? 'dry-bulb'
      : (k.dp !== null && R.ubP[h] > k.dp) ? 'dew point'
      : (k.aq !== null && ds.aq_idx && ds.aq_idx[h] > k.aq) ? 'air quality' : 'dry-bulb';
    out.push(_ev('hour.decide_blocked',
      {bound_c: bound, limit_c: k.limit, short_c: bound - k.limit, binding}));
  }

  const cmd = R.A.modes[h] === 1 ? 'FREE-COOLING' : 'MECHANICAL';
  if(h > 0 && R.A.modes[h] !== R.A.modes[h-1])
    out.push(_ev('hour.act_switch', {command: cmd, n_used: used, budget: k.budget,
                                         dwell_h: k.dwell}));
  else
    out.push(_ev('hour.act_hold', {command: cmd, n_used: used, budget: k.budget}));

  out.push(_ev('hour.score', {truth_c: truth, gap_c: Math.abs(bound - truth),
    side: bound >= truth ? 'above' : 'below',
    covered: bound >= truth ? 'was covered' : 'was NOT covered'}));
  out.push(_ev('hour.recalibrate', {n_shape: tk.n_shape_by_notice[String(k.notice)],
    n_groups: tk.n_groups_by_notice[String(k.notice)]}));
  return out;
}

