# -*- coding: utf-8 -*-
"""N-20  ---  is fleet compute allocation a real decision, or does equal-split win?   FREE, GPU.

THE CLAIM UNDER TEST
    N-9 established ONE genuine sequential decision (when to stage). The second claimed decision is
    resource allocation: you have N facilities and a fixed GPU budget, so you must choose which
    sites get an expensive ensemble today -- and you only learn which ones NEEDED it after spending
    the compute.

    I predicted this would FAIL against equal-split. Equal-split is a famously hard baseline in
    allocation problems, and if most sites are nowhere near their threshold on a typical day it gets
    every decision right while merely wasting compute. Recording the prediction before the result.

PASS CONDITION, FIXED BEFORE THE POLICY WAS WRITTEN
    Beat the BEST of four tuned baselines, out of sample, by more than 2 paired standard errors:
      A equal split
      B rank by forecast mean, top-m  (m tuned)          -- "spend on the hottest sites"
      C rank by |forecast - threshold| ascending, top-m   -- "spend on the marginal sites"
      D random
    Baseline C is the real adversary: the forecast mean is a free proxy for marginality, so the
    two-stage policy only earns anything if a site's UNCERTAINTY carries information the mean does
    not.

WHY THE SITES ARE REAL AND NOT INVENTED DISTRIBUTIONS
    Each facility's true rise distribution is generated by the actual solver over its own geometry
    (separation, bank width, wind exposure) using a large reference ensemble on the GPU. The
    allocation policies then only get to draw a limited number of members each. So the spreads the
    policies exploit are the solver's real spreads, not a convenient parametric assumption.
"""
import sys, time
import numpy as np

from common import banner, save_result, verdict
from solver import Site, downwash_fraction, CALIBRATED
import warp_solver as ws

# RERUN on the CALIBRATED solver. The first run used exchange_s = 20 s and the
# downwash exponent 2.0, both falsified against field data in N-21 and refitted in N-22, so its
# numbers (equal_split 1.1555 vs two_stage 1.2292, -2.0 sigma) are void. The PREDICTION and the
# pass condition are unchanged -- they were fixed before either run. Archived at
# results/n20_fleet_PRECAL_ARCHIVED.json.
AMB = 30.0
DX = 10.0
STEPS = 800
CAL_UC = CALIBRATED["downwash_uc"]
CAL_EXPO = CALIBRATED["downwash_exponent"]
CAL_EXCHANGE_S = CALIBRATED["exchange_s"]
N_SITES = 20
N_REF = 120                 # reference ensemble per site -> the "truth"
TOTAL_BUDGET = 200          # members to distribute across all sites
SCOUT = 3                   # two-stage policy: members spent on every site first
N_TRIALS = 400              # independent days
C_WRONG_HOLD = 1.0          # said "safe" when it was not: an excursion
C_WRONG_STAGE = 0.08        # said "act" when unnecessary: wasted energy
MARGINS = np.arange(-2.0, 2.01, 0.1)


def build(separation_m, bank_w):
    s = Site(2000.0, DX)
    s.add_building(cx=700, cy=1000, w=200, h=120)
    s.add_condensers(cx=700 + 100 + bank_w / 2.0, cy=1000, w=bank_w, h=120,
                     discharge_k=11.0, exchange_s=CAL_EXCHANGE_S)
    nb = 700 + 100 + separation_m
    s.add_building(cx=nb, cy=1000, w=200, h=120)
    return s, (nb - 110.0, 1000.0)


def rise_of(T, site, ix, iy, ambient, r_m=30.0):
    r = max(1, int(r_m / site.dx))
    i, j = int(iy / site.dx), int(ix / site.dx)
    return float(np.mean(T[max(0, i - r):min(site.n, i + r + 1),
                           max(0, j - r):min(site.n, j + r + 1)])) - ambient


def reference_sites(seed=7):
    """Real per-site rise distributions from the solver, one large ensemble each."""
    rng = np.random.default_rng(seed)
    seps = rng.uniform(150, 700, N_SITES)
    banks = rng.uniform(30, 120, N_SITES)
    dirs = 270.0 + rng.normal(0, 25.0, N_SITES)      # each site has its own exposure
    out = []
    for k in range(N_SITES):
        site, intake = build(seps[k], banks[k])
        wf = dirs[k] + rng.normal(0, 20.0, N_REF)
        spd = np.clip(rng.normal(6.0, 2.0, N_REF), 0.3, 14.0)
        scl = rng.uniform(0.5, 1.0, N_REF)
        dw = np.array([downwash_fraction(v, CAL_UC, CAL_EXPO) for v in spd])
        T = ws.solve_batch(site, np.full(N_REF, AMB), spd, wf, scl, steps=STEPS, downwash=dw)
        r = np.array([rise_of(T[m].astype(np.float64), site, intake[0], intake[1], AMB)
                      for m in range(N_REF)])
        out.append({"sep": seps[k], "bank": banks[k], "dir": dirs[k], "pool": r,
                    "true_p90": float(np.percentile(r, 90)), "sd": float(r.std())})
    return out


def draw(site_ref, n, rng):
    """Draw n members from this site's real pool (with replacement)."""
    return rng.choice(site_ref["pool"], size=max(n, 1), replace=True)


def decide(est_p90, threshold_rise, margin=0.0):
    return (est_p90 + margin) > threshold_rise      # True = stage


def cost_of(decisions, truths, threshold_rise):
    c = 0.0
    for d, t in zip(decisions, truths):
        breach = t > threshold_rise
        if breach and not d:
            c += C_WRONG_HOLD
        elif d and not breach:
            c += C_WRONG_STAGE
    return c


# ------------------------------------------------------------------ allocators
def alloc_equal(_scout_est, _scout_sd):
    return np.full(N_SITES, TOTAL_BUDGET // N_SITES)


def alloc_topm_by_mean(scout_est, _sd, m):
    a = np.zeros(N_SITES, dtype=int)
    idx = np.argsort(-scout_est)[:m]
    a[idx] = TOTAL_BUDGET // max(m, 1)
    return a


def alloc_topm_by_marginality(scout_est, _sd, m, thr):
    a = np.zeros(N_SITES, dtype=int)
    idx = np.argsort(np.abs(scout_est - thr))[:m]
    a[idx] = TOTAL_BUDGET // max(m, 1)
    return a


def alloc_random(_est, _sd, rng):
    w = rng.dirichlet(np.ones(N_SITES))
    return np.maximum((w * TOTAL_BUDGET).astype(int), 1)


def alloc_two_stage(scout_est, scout_sd, thr):
    """The proposed policy: weight by the chance more samples would FLIP the decision.

    A site far from threshold cannot flip however much you sample it. A site near threshold with a
    wide spread is where compute changes the answer. This uses the scout SD, which is the
    information the mean-based baselines do not have.
    """
    z = np.abs(scout_est - thr) / np.maximum(scout_sd, 1e-3)
    w = np.exp(-0.5 * z ** 2)                       # peaks where the decision is marginal
    if w.sum() <= 0:
        return np.full(N_SITES, TOTAL_BUDGET // N_SITES)
    a = np.maximum((w / w.sum() * TOTAL_BUDGET).astype(int), 1)
    return a


def run_trials(refs, thr, allocator, n_trials, seed, margin=0.0):
    rng = np.random.default_rng(seed)
    per_day = []
    for _ in range(n_trials):
        scout = [draw(r, SCOUT, rng) for r in refs]
        est = np.array([np.percentile(s, 90) for s in scout])
        sd = np.array([s.std(ddof=1) if len(s) > 1 else 1.0 for s in scout])
        alloc = allocator(est, sd)
        truths, decisions = [], []
        for k, r in enumerate(refs):
            n = int(alloc[k])
            samp = np.concatenate([scout[k], draw(r, n, rng)]) if n > 0 else scout[k]
            decisions.append(decide(float(np.percentile(samp, 90)), thr, margin))
            truths.append(float(rng.choice(r["pool"])))
        per_day.append(cost_of(decisions, truths, thr))
    return np.array(per_day)


def best_margin(refs, thr, allocator, seed):
    best = (None, float("inf"))
    for m in MARGINS:
        c = run_trials(refs, thr, allocator, 120, seed, float(m)).mean()
        if c < best[1]:
            best = (float(m), c)
    return best


def main():
    banner("N-20  Fleet compute allocation: real decision, or does equal-split win?  [FREE, GPU]")
    if not ws.HAVE_WARP:
        print("   warp-lang unavailable."); return 2
    print("   PREDICTION RECORDED BEFORE RUNNING: this will FAIL against equal-split or")
    print("   against ranking by marginality. Reporting whatever happens.")

    t0 = time.time()
    refs = reference_sites()
    p90s = np.array([r["true_p90"] for r in refs])
    sds = np.array([r["sd"] for r in refs])
    thr = float(np.median(p90s))
    print("\n   %d facilities, real solver distributions (%d reference members each, %.0f s GPU)"
          % (N_SITES, N_REF, time.time() - t0))
    print("      true p90 rise across sites: %.3f to %.3f C   (threshold set at median %.3f)"
          % (p90s.min(), p90s.max(), thr))
    print("      per-site sd: %.3f to %.3f C   -> spread DOES vary across sites by %.1f x"
          % (sds.min(), sds.max(), sds.max() / max(sds.min(), 1e-6)))
    print("      budget %d members over %d sites (%d each if split equally); scout %d each"
          % (TOTAL_BUDGET, N_SITES, TOTAL_BUDGET // N_SITES, SCOUT))

    rng_r = np.random.default_rng(99)
    fams = {
        "equal_split": lambda m: (lambda e, s: alloc_equal(e, s)),
        "top_m_by_mean": lambda m: (lambda e, s: alloc_topm_by_mean(e, s, 6)),
        "top_m_marginal": lambda m: (lambda e, s: alloc_topm_by_marginality(e, s, 6, thr)),
        "random": lambda m: (lambda e, s: alloc_random(e, s, rng_r)),
    }
    print("\n   TUNING each baseline's decision margin on TRAINING days, scoring on HELD-OUT days")
    base_res = {}
    for name, mk in fams.items():
        bm, bc = best_margin(refs, thr, mk(None), 11)
        held = run_trials(refs, thr, mk(None), N_TRIALS, 5000, bm)
        base_res[name] = {"margin": bm, "train": bc, "test": held.mean(), "per_day": held}
        print("      %-16s best margin %+.2f   train %.4f   HELD-OUT %.4f"
              % (name, bm, bc, held.mean()))

    two = lambda e, s: alloc_two_stage(e, s, thr)
    bm2, bc2 = best_margin(refs, thr, two, 11)
    held2 = run_trials(refs, thr, two, N_TRIALS, 5000, bm2)
    print("      %-16s best margin %+.2f   train %.4f   HELD-OUT %.4f"
          % ("two_stage", bm2, bc2, held2.mean()))

    best_name = min(base_res, key=lambda k: base_res[k]["test"])
    best = base_res[best_name]
    d = best["per_day"] - held2
    gain, se = float(d.mean()), float(d.std(ddof=1) / np.sqrt(len(d)))
    sigma = gain / max(se, 1e-12)

    print("\n   RESULT")
    print("      best baseline           : %s at %.4f" % (best_name, best["test"]))
    print("      two-stage policy        : %.4f" % held2.mean())
    print("      gain (paired, held-out) : %+.4f +/- %.4f  = %.1f sigma" % (gain, se, sigma))

    ok = sigma > 2.0
    print("\n   VERDICT AGAINST THE PRE-COMMITTED CONDITION (>2 sigma over the best baseline)")
    print()
    verdict(ok,
            "PASS - allocation is a real decision: weighting by decision-flip probability beats the "
            "best tuned baseline (%s) by %+.4f +/- %.4f (%.1f sigma) on held-out days. The "
            "prediction that this would fail was wrong." % (best_name, gain, se, sigma),
            "FAIL - as predicted. The best simple baseline (%s) matches or beats the two-stage "
            "policy (%+.4f +/- %.4f, %.1f sigma). Do NOT claim fleet allocation as a second agentic "
            "decision; the forecast mean is already a sufficient proxy for marginality."
            % (best_name, gain, se, sigma))

    save_result("n20_fleet.json", {
        "prediction": "expected to FAIL against equal-split / marginality ranking",
        "n_sites": N_SITES, "n_ref": N_REF, "budget": TOTAL_BUDGET, "scout": SCOUT,
        "n_trials": N_TRIALS, "threshold_rise": thr,
        "true_p90_range": [float(p90s.min()), float(p90s.max())],
        "site_sd_range": [float(sds.min()), float(sds.max())],
        "baselines": {k: {"margin": v["margin"], "train": v["train"], "test": float(v["test"])}
                      for k, v in base_res.items()},
        "two_stage": {"margin": bm2, "train": bc2, "test": float(held2.mean())},
        "best_baseline": best_name, "gain": gain, "se": se, "sigma": sigma, "pass": ok})
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
