/* GENERATED by tools/make_globe_poster.py from demo/textures/earth_daymap.jpg. Do not edit.
 *
 * 🔴 WHY A PICTURE OF THE EARTH IS COMPILED INTO THE JAVASCRIPT.
 * `HeatGlobe` starts drawing on the frame it mounts, and `THREE.TextureLoader` has by then only
 * returned an EMPTY Texture. A WebGL sampler bound to an incomplete texture reads (0, 0, 0, 1), and
 * the material multiplies its white base colour by that, so the sphere is BLACK until
 * earth_daymap.jpg has been fetched, decoded and uploaded. The user reported exactly that: "it shows
 * a black space in place of globe when the website is loaded".
 * A data URI inside the bundle needs no request, so this map is in memory before the component runs
 * and the only remaining cost is one frame of decode.
 *
 * 128x64, 2681 bytes of JPEG. It is deliberately SOFT: it exists to be correct in colour and continent
 * placement for a few hundred milliseconds, and `HeatGlobe` swaps the full 2048x1024 map in as soon
 * as that decodes. Because both are the same photograph, the swap reads as the image coming into
 * focus rather than as one picture replacing another.
 *
 * Re-run the generator after any change to the shipped texture, or the poster becomes a different
 * planet from the one it is standing in for.
 */
export const POSTER_DAY =
  'data:image/jpeg;base64,' +
  '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBAUEBAYFBQUGBgYHCQ4JCQgICRINDQoOFRIWFhUSFBQXGiEcFxgfGRQUHScd' +
  'HyIjJSUlFhwpLCgkKyEkJST/2wBDAQYGBgkICREJCREkGBQYJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQk' +
  'JCQkJCQkJCQkJCQkJCT/wAARCABAAIADASIAAhEBAxEB/8QAHAAAAAcBAQAAAAAAAAAAAAAAAAMEBQYHCAIB/8QAOhAAAgED' +
  'AwIEBAQEAwkAAAAAAQIDAAQRBRIhBjEHQVFhExQikTJxgaEIFRcjFlKxJDM0QnLB4fDx/8QAGgEAAgMBAQAAAAAAAAAAAAAA' +
  'AwQBAgUABv/EAC8RAAEDAwIEAwgDAQAAAAAAAAEAAgMEESESMQUTQWEUFVEiIzJScYGh0UJikcH/2gAMAwEAAhEDEQA/ALqv' +
  'PELpqwnFvPqdss+MmMN9QHuPKktz4qdK2ibpr9APVQW/0rJi6rdGYSzzyTkLt/uMWOPTOaOj1ko3/B2zLjAzuDD33Ag5rSko' +
  'ZQ6zACPqlG1LbZWq9L8VOmtXldLeaYBWChpEKB8gngkduO5xTs3VlgciKeFyBnAO4/tWRFvJ76aM20zQbE5J7jkckqBkc9z+' +
  'VSCfWOrdAtmxdb1C/TLC31rnz9z+eaznTNY/RILFHFyNQyr21/xKvNMMaWWjtqch+p0tpU3pHkjcELbm5B7ccV70b4raF1xe' +
  'Np1vLfWN8g4guIwhl9duCe2DwcGs56P1dc2t7LeXjz3Vw0Xw0nY/3YsZwc+ffscg0Vb9U3+kdRDqDSLu4jugc77jDsSVwwI7' +
  'FTzxjjj0p+NsUpMbDn1z+UAyOb7R2Wstb1K10a0e5ur14UUZyzjP71Q+pfxBdQx38qaato9ojFUaZCzOM8E4xj7VWus63qHU' +
  'F/Lf6ndSXM8rlyXYkKT5KOyj2FFxs1/cItzOckBFJH2HFOR0jYml0mUJ85dhuFaum/xCa/JI63dlHIduY1tY8kn33Ht7iibz' +
  '+IPq5ZGEdlZxR5+nfGxYD3IOM1AE0u6jiWASRws2Q+wHLjvyfP8AKu4un5ZSdtxww+nnk/pWXPxKnjf7DQQiBryMlWJb+N/V' +
  'k1kbkrYqWfakaxvJJwOSVUcDngkjPlnmnmw8SPEjULkwRadokW1trSzTrsH2c+XpVZ2nRupSFWgnuCvIYqcjjy4rq46X1MKs' +
  'cckzuThU24OfvS54q07RgIwgfa5JV9/4p6gjiX5ifQY58AlPmGZX/wA2CQuPsabV8XriFZvjaFLM0GDILW9glwPXhu3r6VSL' +
  '6B1HHJG0y3Ey9sxjewX1HlXN1ZXelyyYS8hyNpO8Etny7c9s4oPmFsloVzGQOqvz+sukJFC8lnexiRQxygZkz5FQc/tS/S/F' +
  'zpjUZlgW9cSsdoDW8gGfzK1mqfqy6mSO3eKzeFcAO0WW4GMk5Gcfaubnqy+DNFZy/DhGApKKG4HJ44GfYVqRU00gB0ix7n9F' +
  'AMzR1TFQoUK30gnrpPWYNF1VZbmESQSD4bnjKD154NTXqXWLVdGjv7Z1ZXf4YIHYjjH2qsKURXs0UBtwwaFmDGNhkZ9fY1k1' +
  '/C21DtY369x+01FVFjCwpRqF610gkVcIxxwAAvt/5pvpdaQJdM7Gb5eJRlt3Iz+v/wBpPNAEb+24lTGQwGMj8vKrUj6enPhw' +
  'bO77577ILmud7SJqd+G3QuodQStqBiSKw5hWaWMOHfI4UE9x61BKsTojxTuOmtJi0tljEMO4gsu4ncxPHp3NE4o6QU5EYuT9' +
  '8ItJo5gMhwpJqPgtJI8H8k1lvilwbj59SR3HKlR5DPHv3FdaX4appOsRW3Uc+mTtOrNaXFsJPiSsuO5PAwD+Hv8AY0Z/W22a' +
  'zZfloZi57vnKkdsZ7HjNE3PXL9X/AC7w7YEtnEqyg8xOvY/9OMg+xryxqpL8qTB22sVqhkJOpidrVbHpU3emXF6bSNrh5ALo' +
  'bIwWA/ATjKsOeCe5oy3Njpcssd7bRTufqWZfrwMdiO4PuOD7VVXiD1rqnU+oNaXGppd2Ns/9pYYvhxFsYLAZJPmAST+maaW6' +
  'huTocenLI6sjnLg8tGRwufY5rSPCJHNa8HJ37BLmta0ltsDZWPqPXSpPKulxRKgGCQpXbz3HHeoF1TrMl/dbRcTSRkZ2ufwt' +
  'nkj86QLqTmxMUiFnwEjlUkMuOw/LvSA42D/Nn7ir0PDdExMxBtgD/v8AqXnqnPbYLljnGOAPKvKFCvRgACwSKFChQqVyFChQ' +
  'rlycNLtV1UrppnWCaSQGBmB2s542HHbPGD2B796cNO0GS3u3WYkGJiro3kRx5e9IOnWCa5YyHjZKH7Z5HI/cU4dQanblpIrZ' +
  'meVyTK+SMHOSPc5rzfEqHm1IEQycn0+qegc0R6n9E3a2YBefDghWP4ahWK/859ab6FCt+CLlRhl72Sb3anEp76Z0yTVGuokE' +
  'bhUUlGPJBPcf++lLtVjfStNlssCBpjtCqOW5/D+Rpn0HWp9A1FL2ABiAVZT2ZT5fcA/pXuta3NrN0J2URBfwqp8/XPrWXNw9' +
  '76wSj4cH7hNsnY2DT/JIbiFreZ4WILIdpx2zRdesxZizElicknzNeVsNBAF90kbXwu0kMecYIPcGnXTOnL/V1MoT4UQP+8k8' +
  '/wAh50z96kSdZXEccaLbqzKqqzMx5IGD2pKsZLa8DQXHr6Jin5RPvThINX0e90pYjd24j35AZRwcHz8uRzTbUp6i6uh1vT1j' +
  'WD4crAKy4+lMenvxUXVGYFsfSO58hUUD5OUea3SQV1S1gf7s3C5oVbf9Ar0HJl1Lb6fLx5P67z/pUi0fwC0IQ7tRGszS5/CJ' +
  'VjAHpwnNXNfCOqqKd56Kgq9rSy+BnRWzB0u/GPNrtyaUaf4J9G2ayq2jyXayYI+alZimP8pGCKH5lF6FX8K9Zr03UZNLufmI' +
  '1QsUaM7h5MMHHofei7qzubQp81BJC0i71Eg2synscHnBrS6+Fuh6Pd/OaL09ZCYE4+ZklkQAjBwCSKjXU/hLrPW2vvqeoLDY' +
  'uUCM1u+VYKMDCkcfqaq2viL72t3UmnfptdUPXlXjpP8ADqkc4fVL25miDZ+HCVQke5wf2qf6R4XdJaTFtXpizlbAy88Zmc49' +
  '2zirv4jEPhyqtpXnfCyfkeo+9eblHdh962EekOmgCP8ACmmYIwf9jjH/AGoy06d0OwMZsunrCAxtuXbbJlT6g470LzNvyq/h' +
  'D6rH72txHEkz28yxPnZI0bBWx3wcYNcxRSXD7IY3lfvtjUsfsK2nPJNcRfCYSqvooAA/Lik+l6bb6NGyWFhBb7/xusYDv7s3' +
  'dj7k1XzT+v5U+E7rHn8p1HYH/l97sOMN8u+D+1CPSdRm3/D069f4Zw+23c7T6HA4rZ6zTDh/iup7rg0Y97MybEQxKe4GRmo8' +
  '0Py/lT4QeqxJNFJbNtnjeFvSRSp/eudxK4B479+K2vcxi8jCT20NyAMBZUDj9xVTdX+EMnUWpSzxWaWEe4tHHYWsKDnvubgt' +
  '6+1Fj4kxxs8WVHUpGxuv/9k='

/** What it was made from and at what size, so a reader does not have to open the generator. */
export const POSTER_META = { width: 128, height: 64, bytes: 2681, source: 'demo/textures/earth_daymap.jpg' }
