# -*- coding: utf-8 -*-
"""Keep CONTEXT/ honest. Two modes: --write regenerates what is derived, --check fails if it drifted.

WHY THIS EXISTS RATHER THAN A PROMISE TO REMEMBER. CONTEXT/ is the folder a future session reads to
recover this project's state, and a context pack that has quietly drifted from the artefacts is worse
than no context pack at all: it does not merely fail to help, it actively misinforms, and it does so
with the authority of a document that says "read this first". Every figure in the pack that can be
re-derived is therefore re-derived here and compared, so the pack cannot rot silently.

WHAT IS DERIVED (regenerated by --write, asserted by --check):
  1. CONTEXT/MEMORY-MIRROR.md -- the full text of the auto-memory files, which live OUTSIDE the repo
     at ~/.claude/projects/d--FGHackathon/memory/ because that is where the memory mechanism reads
     them. They are mirrored in rather than moved so there is exactly one source of truth and the
     mirror is generated, never hand-edited.
  2. The FIGURES block in CONTEXT/01-STATE.md -- counts that come from the shipped artefacts
     (facilities, offerable sites, states, run_all steps, page size) rather than from anyone's memory.

WHAT ELSE IS ASSERTED (checked, never regenerated):
  * every file the pack is supposed to contain, including the two deep-reference documents that moved
    in from the repo root and that audit.py now opens through a CONTEXT/ path;
  * that CLAUDE.md still exists at the repository root and still points at 00-START-HERE.md, because
    that file is the only reason this pack gets read at all;
  * two standing rules that happen to be mechanically checkable: the live-agent card and button are
    still in demo/index.html, and the map still has the second, flat GeoJSON source the per-state view
    depends on.

WHAT IS NOT DERIVED. The prose. Judgement, history and reasoning cannot be regenerated from files and
are not asserted here; --check verifies the numbers and the structure, and says plainly that it does
not verify the prose. A check that claimed otherwise would be the same kind of lie it exists to
prevent.

Exit 0 clean, 1 drifted (with a diff), 2 could not run.
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEMO = os.path.join(ROOT, "AGENTIC-ARBITER", "demo")
SRC = os.path.join(ROOT, "AGENTIC-ARBITER", "src")
MEMDIR = os.path.expanduser(
    os.path.join("~", ".claude", "projects", "d--FGHackathon", "memory"))

MIRROR = os.path.join(HERE, "MEMORY-MIRROR.md")
STATE = os.path.join(HERE, "01-STATE.md")

# The pack's own files. Named here so --check can report a missing one instead of silently passing a
# folder that has lost half its contents.
REQUIRED = [
    "00-START-HERE.md",
    "01-STATE.md",
    "02-ARCHITECTURE.md",
    "03-VERIFICATION.md",
    "04-STANDING-RULES.md",
    "05-TRAPS.md",
    "06-GLOSSARY.md",
    "MEMORY-MIRROR.md",
    "sync_context.py",
    # The two deep-reference documents. They MOVED here from the repo root on 2026-08-28, and
    # audit.py plus testing/bump_spend_docs.py open both by a path with "CONTEXT" joined into it. If
    # someone moves them back out, those two break and every pointer in this pack goes stale, so
    # their presence is asserted here rather than assumed.
    "HANDOFF.md",
    "READING-THE-AGENT.md",
]

# 🔴 THE AUTO-REREAD MECHANISM ITSELF. CLAUDE.md at the repository root is loaded automatically every
# session and after every context compaction, and it is the ONLY reason "read CONTEXT/ first" is a
# behaviour rather than an intention. Delete it and the pack silently stops being read, with nothing
# anywhere reporting that anything is wrong -- which is the worst failure mode a context pack has. So
# the check asserts the file exists and still points at this folder's entry point.
CLAUDE_MD = os.path.join(ROOT, "CLAUDE.md")
CLAUDE_MUST_MENTION = ["CONTEXT/00-START-HERE.md", "sync_context.py"]

FIG_START = "<!-- FIGURES:BEGIN -- generated by sync_context.py, do not hand-edit -->"
FIG_END = "<!-- FIGURES:END -->"
MIR_HEAD = "<!-- MIRROR -- generated by sync_context.py from the auto-memory dir. Do not hand-edit. -->"


# ---------------------------------------------------------------------------------------------
#  THE DERIVED FIGURES, each read from the artefact that owns it
# ---------------------------------------------------------------------------------------------
def figures():
    """Every number in the pack that a file can settle. Read, never remembered."""
    f = {}

    uni = os.path.join(DEMO, "unified_sites.json")
    sites = os.path.join(DEMO, "sites.json")
    page = os.path.join(DEMO, "index.html")
    runall = os.path.join(SRC, "run_all.py")

    for p in (uni, sites, page, runall):
        if not os.path.exists(p):
            raise SystemExit("cannot run: missing %s" % p)

    u = json.load(io.open(uni, encoding="utf-8"))
    s = json.load(io.open(sites, encoding="utf-8"))
    rows = u["sites"]

    f["facilities"] = len(rows)
    # THE SAME RULE THE PAGE USES. index.html's siteIsRunnable() is
    # `SITES.sites.some(x => x.key === metroKey && x.offerable)`, so "ready to run" is a property of
    # sites.json, not of unified_sites.json's baked `status` string. Deriving it from the wrong file
    # is a mistake this project has already made once, on the map's dot colours.
    offerable = {x["key"] for x in s["sites"] if x.get("offerable")}
    f["offerable_metros"] = len(offerable)
    f["ready_facilities"] = sum(1 for x in rows if x.get("metro_key") in offerable)
    f["states"] = len({x.get("state") or "??" for x in rows})

    src = io.open(page, encoding="utf-8", newline="").read()
    f["page_kb"] = int(round(len(src.encode("utf-8")) / 1024.0))
    # The steps are COUNTED in run_all.py's own STEPS list rather than read from a doc.
    ra = io.open(runall, encoding="utf-8", newline="").read()
    f["run_all_steps"] = len(re.findall(r"^    \(\"", ra, re.M))

    # The live-agent surface must still exist: it is a standing instruction that it is never removed,
    # so the pack states it as a measured fact rather than as an intention.
    f["livecard_present"] = int('id="livecard"' in src)
    f["livego_present"] = int('id="livego"' in src)

    # The map's two sources, which is the design decision most likely to be undone by accident.
    f["map_sources"] = len(re.findall(r"map\.addSource\('unisites", src))
    f["map_layers"] = len(re.findall(r"id:'unisites-", src))
    return f


def figures_block(f):
    """The generated table, exactly as it must appear between the markers in 01-STATE.md."""
    rowsrc = [
        ("Real facilities in the registry", f["facilities"], "demo/unified_sites.json -> len(sites)"),
        ("Of those, ready to run", f["ready_facilities"],
         "sites.json offerable metros, joined on metro_key"),
        ("Offerable metros", f["offerable_metros"], "demo/sites.json -> sites[].offerable"),
        ("States represented", f["states"], "distinct unified_sites.json sites[].state"),
        ("run_all.py steps", f["run_all_steps"], "count of STEPS entries in src/run_all.py"),
        ("demo/index.html size", "%d KB" % f["page_kb"], "byte length of the shipped page"),
        ("Map GeoJSON sources", f["map_sources"],
         "one clustered, one flat -- see 02-ARCHITECTURE"),
        ("Map unisites-* layers", f["map_layers"], "cluster, halo, points, flat-halo, flat"),
        ("`#livecard` present", "yes" if f["livecard_present"] else "NO -- RULE BROKEN",
         "standing rule: the live agent is never removed"),
        ("`#livego` present", "yes" if f["livego_present"] else "NO -- RULE BROKEN",
         "standing rule: the live agent is never removed"),
    ]
    out = [FIG_START,
           "",
           "| Figure | Value | Derived from |",
           "|---|---:|---|"]
    for name, val, prov in rowsrc:
        out.append("| %s | **%s** | %s |" % (name, val, prov))
    out += ["",
            "*Every row above is re-read from the artefact named beside it by "
            "`CONTEXT/sync_context.py`. None of it is typed by hand, so none of it can go stale "
            "without the check failing.*",
            "",
            FIG_END]
    return "\n".join(out)


# ---------------------------------------------------------------------------------------------
#  THE MEMORY MIRROR
# ---------------------------------------------------------------------------------------------
def memory_mirror():
    if not os.path.isdir(MEMDIR):
        raise SystemExit("cannot run: no auto-memory dir at %s" % MEMDIR)
    names = sorted(n for n in os.listdir(MEMDIR)
                   if n.endswith(".md") and n != "MEMORY.md")
    body = [MIR_HEAD,
            "",
            "# The auto-memory, mirrored",
            "",
            "**Source of truth:** `~/.claude/projects/d--FGHackathon/memory/`. These files live "
            "outside the repository because that is where the memory mechanism reads them; editing "
            "this mirror changes nothing. Edit the source, then run "
            "`python CONTEXT/sync_context.py --write`.",
            "",
            "**Why mirror them at all.** The memory files are loaded automatically, but only their "
            "one-line index is guaranteed to be in context. The full text matters when a rule has to "
            "be applied rather than merely recalled, and this is where a session that has lost its "
            "history can read all of it at once.",
            "",
            "---",
            ""]
    idx = os.path.join(MEMDIR, "MEMORY.md")
    if os.path.exists(idx):
        body += ["## The index (`MEMORY.md`)", "", "```markdown",
                 io.open(idx, encoding="utf-8").read().rstrip(), "```", "", "---", ""]
    for n in names:
        txt = io.open(os.path.join(MEMDIR, n), encoding="utf-8").read().rstrip()
        body += ["## `%s`" % n, "", "```markdown", txt, "```", ""]
    body += ["---", "",
             "*%d memories mirrored, plus the index.*" % len(names), ""]
    return "\n".join(body) + "\n"


# ---------------------------------------------------------------------------------------------
def splice(text, start, end, block):
    i, j = text.find(start), text.find(end)
    if i < 0 or j < 0:
        return None
    return text[:i] + block + text[j + len(end):]


def main():
    write = "--write" in sys.argv
    check = "--check" in sys.argv or not write
    problems, notes = [], []

    missing = [n for n in REQUIRED if not os.path.exists(os.path.join(HERE, n))]
    if missing and check and not write:
        problems.append("CONTEXT/ is missing: %s" % ", ".join(missing))

    try:
        f = figures()
    except SystemExit as e:
        print("   %s" % e)
        return 2

    # ---- the memory mirror ----
    want = memory_mirror()
    have = io.open(MIRROR, encoding="utf-8").read() if os.path.exists(MIRROR) else None
    if write:
        io.open(MIRROR, "w", encoding="utf-8", newline="\n").write(want)
        notes.append("MEMORY-MIRROR.md written (%d bytes)" % len(want))
    elif have != want:
        if have is None:
            problems.append("MEMORY-MIRROR.md does not exist")
        else:
            problems.append("MEMORY-MIRROR.md has drifted from the auto-memory dir "
                            "(%d bytes on disk, %d expected)" % (len(have), len(want)))

    # ---- the figures block in 01-STATE.md ----
    if os.path.exists(STATE):
        cur = io.open(STATE, encoding="utf-8", newline="").read()
        block = figures_block(f)
        if FIG_START not in cur or FIG_END not in cur:
            problems.append("01-STATE.md has no FIGURES block to keep current")
        else:
            new = splice(cur, FIG_START, FIG_END, block)
            if write:
                if new != cur:
                    io.open(STATE, "w", encoding="utf-8", newline="\n").write(new)
                    notes.append("01-STATE.md figures refreshed")
                else:
                    notes.append("01-STATE.md figures already current")
            elif new != cur:
                problems.append("01-STATE.md's figures no longer match the artefacts")
    elif not write:
        problems.append("01-STATE.md does not exist")

    # ---- the mechanism that makes this pack get read at all ----
    if not os.path.exists(CLAUDE_MD):
        problems.append("CLAUDE.md is MISSING from the repository root. It is what makes an "
                        "assistant read CONTEXT/ at the start of a session and after a compaction; "
                        "without it this pack is a folder nobody opens.")
    else:
        cm = io.open(CLAUDE_MD, encoding="utf-8").read()
        absent = [t for t in CLAUDE_MUST_MENTION if t not in cm]
        if absent:
            problems.append("CLAUDE.md no longer points at %s, so the read-this-first instruction "
                            "is broken" % ", ".join(absent))

    # ---- the two standing rules that are mechanically checkable ----
    if not f["livecard_present"] or not f["livego_present"]:
        problems.append("THE LIVE AGENT IS MISSING from demo/index.html "
                        "(#livecard=%d, #livego=%d) -- this is a standing instruction, "
                        "never a refactor decision" % (f["livecard_present"], f["livego_present"]))
    if f["map_sources"] < 2:
        problems.append("the map has %d GeoJSON source(s); the state view needs the second, FLAT "
                        "one because maplibre cannot un-cluster a source after creation "
                        "(see 02-ARCHITECTURE)" % f["map_sources"])

    print("=" * 78)
    print("CONTEXT PACK -- %s" % ("WRITE" if write else "CHECK"))
    print("=" * 78)
    for k in sorted(f):
        print("   %-22s %s" % (k, f[k]))
    for n in notes:
        print("   [ok]   %s" % n)
    print()
    if problems:
        for p in problems:
            print("   [DRIFT] %s" % p)
        print()
        print("VERDICT: the context pack has drifted. Run "
              "`python CONTEXT/sync_context.py --write`, then re-read what changed and fix the "
              "PROSE by hand -- this tool only regenerates the derived parts.")
        return 1
    print("VERDICT: every derived figure in CONTEXT/ matches the artefact it came from, and the "
          "memory mirror matches its source.")
    print("   NOT CHECKED HERE, stated rather than implied: the PROSE. Judgement and history cannot "
          "be re-derived from files, so nothing here asserts that the narrative is still accurate.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
