# -*- coding: utf-8 -*-
"""Bake a tiny Earth into the bundle, so the globe is never a black disc.

🔴 THE PROBLEM THIS SOLVES, AND WHY A SMALLER TEXTURE WOULD NOT HAVE SOLVED IT.
The user: "The globe should appear immediately, it shows a black space in place of globe when the
website is loaded and globe takes time to render."

They are right, and the black is not a slow render. `HeatGlobe.tsx` starts its draw loop on the frame
the component mounts, while `THREE.TextureLoader` has only RETURNED a Texture object and not yet
decoded anything into it. A WebGL sampler bound to an incomplete texture reads (0, 0, 0, 1), and
`MeshPhongMaterial` multiplies its white base colour by that, so the sphere renders BLACK until the
first byte of `earth_daymap.jpg` has arrived, decoded and uploaded. The four maps are 1.2 MB and
2048x1024 each; even halving them leaves a network round trip in front of the first frame.

So the fix is not a faster texture, it is a texture that needs no network at all. This tool writes a
128x64 JPEG of the day map as a base64 data URI into a TypeScript module, which means it is INSIDE
the JavaScript bundle: by the time `HeatGlobe` runs, the bytes are already in memory and the only
remaining cost is a decode, which is one frame.

⚠ IT IS A POSTER, NOT A REPLACEMENT. 128x64 across a globe drawn about 900 px wide is roughly seven
texels per hundred pixels, so it is soft: continents are placed and coloured correctly and nothing
smaller than a large island is legible. The full 2048x1024 map replaces it the moment it decodes, and
the change reads as focus rather than as a swap, which is the point of choosing the SAME image
downscaled rather than a flat colour or a gradient.

⚠ AND IT IS GENERATED, NOT DRAWN BY HAND. The poster is a resample of the shipped texture, so it
cannot drift from it: re-run this after any change to `demo/textures/earth_daymap.jpg` and the two
stay the same planet. `run_all.py` does not run it, for the same reason it does not run
`make_earth_textures.py`: both write source files that are then committed, and a build step that
rewrites tracked source on every run is a build step that produces spurious diffs.

Run from the repository root:  python tools/make_globe_poster.py
"""
import base64
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "AGENTIC-ARBITER", "demo", "textures", "earth_daymap.jpg")
OUT = os.path.join(ROOT, "AGENTIC-ARBITER", "app", "src", "intro", "globePoster.ts")

# 🔴 128x64 IS A MEASURED COMPROMISE, NOT A ROUND NUMBER. At 64x32 the Mediterranean closes up and
# Britain disappears; at 256x128 the data URI passes 16 KB, which is real weight in a module that
# exists to be available before anything else. 128x64 keeps every continent's silhouette and the
# whole thing costs about 5 KB of base64.
W, H = 128, 64
QUALITY = 82


def main():
    try:
        from PIL import Image
    except ImportError:
        print("Pillow is required: python -m pip install pillow")
        return 1
    if not os.path.isfile(SRC):
        print("missing %s" % os.path.relpath(SRC, ROOT))
        return 1

    im = Image.open(SRC).convert("RGB")
    print("   source            %s  %dx%d  %d KB"
          % (os.path.relpath(SRC, ROOT), im.width, im.height,
             round(os.path.getsize(SRC) / 1024)))

    # LANCZOS rather than the default: a box filter over an 16x downscale turns coastlines into mush,
    # and the whole value of a poster is that the coastlines are recognisable.
    small = im.resize((W, H), Image.LANCZOS)
    buf = io.BytesIO()
    small.save(buf, format="JPEG", quality=QUALITY, optimize=True, progressive=False)
    raw = buf.getvalue()
    b64 = base64.b64encode(raw).decode("ascii")
    uri = "data:image/jpeg;base64," + b64
    print("   poster            %dx%d  %d bytes JPEG  %d bytes base64  (%.1f KB in the bundle)"
          % (W, H, len(raw), len(b64), len(uri) / 1024.0))

    # Wrapped so the generated file is readable in a diff rather than one 5,000-character line.
    lines = [b64[i:i + 96] for i in range(0, len(b64), 96)]
    body = "\n".join("  '%s' +" % ln for ln in lines[:-1] + [lines[-1]])
    body = body.rstrip(" +")

    ts = '''/* GENERATED by tools/make_globe_poster.py from demo/textures/earth_daymap.jpg. Do not edit.
 *
 * 🔴 WHY A PICTURE OF THE EARTH IS COMPILED INTO THE JAVASCRIPT.
 * `HeatGlobe` starts drawing on the frame it mounts, and `THREE.TextureLoader` has by then only
 * returned an EMPTY Texture. A WebGL sampler bound to an incomplete texture reads (0, 0, 0, 1), and
 * the material multiplies its white base colour by that, so the sphere is BLACK until
 * earth_daymap.jpg has been fetched, decoded and uploaded. The user reported exactly that: "it shows
 * a black space in place of globe when the website is loaded".
 * A data URI inside the bundle needs no request, so this map is in memory before the component runs
 * and the only remaining cost is one frame of decode.
 *
 * %dx%d, %d bytes of JPEG. It is deliberately SOFT: it exists to be correct in colour and continent
 * placement for a few hundred milliseconds, and `HeatGlobe` swaps the full 2048x1024 map in as soon
 * as that decodes. Because both are the same photograph, the swap reads as the image coming into
 * focus rather than as one picture replacing another.
 *
 * Re-run the generator after any change to the shipped texture, or the poster becomes a different
 * planet from the one it is standing in for.
 */
export const POSTER_DAY =
  'data:image/jpeg;base64,' +
%s

/** What it was made from and at what size, so a reader does not have to open the generator. */
export const POSTER_META = { width: %d, height: %d, bytes: %d, source: 'demo/textures/earth_daymap.jpg' }
''' % (W, H, len(raw), body, W, H, len(raw))

    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(ts)
    print("   wrote             %s  (%.1f KB)"
          % (os.path.relpath(OUT, ROOT), os.path.getsize(OUT) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
